### ISSUE TITLE
irdcheck python3 error

### ISSUE THREAD

**Issue by thomasbra1** [flesniak/ps3-tools#1]
Using Ubuntu 18.04

  I was attempting to run the irdcheck.py program but I keep getting this error:
 python3 irdcheck.py 

Traceback (most recent call last):
  File "irdcheck.py", line 13, in <module>
    import iso
  File "/media/4TB12/PS3/redump-dats/tt/irdcheck/iso.py", line 187, in <module>
    c.Embedded(EntityIDHeader),
AttributeError: module 'construct' has no attribute 'Embedded'

Also,  what are the python dependancy needed to be installed for the tools?

Thanks.

Update:

https://construct.readthedocs.io/en/latest/

Seems that Embedded has been removed since January 2020

Version 2.10 was released in January 2020. It removes major neckpains (Embedded and EmbeddedSwitch). See Transition page.

**Comment by flesniak** [comment]
Hi,
thanks for reporting. I lost track of all the projects I've been using construct in. I removed all occurences of Embedded and did a quick test. Can you also try latest master?

**Comment by thomasbra1** [comment]
That fixed the issue.  I tested it with a ird and game directory. Thanks for the quick reply and fix.
